### ISSUE TITLE
Feature request - support Labels

### ISSUE THREAD

**Issue by feldsam** [marthjod/ansible-one-inventory#1]
Hello, I try to use this inventory and I decided to use OpenNebula VM Labels to create VM groups. I was playing with regex but end up with this:

## VM Lables:

    Cloud
    WebServers
    DbServers
    
    and combinations

 
## Config:
    
    hostname_field_in_user_template: "LABELS"
    
    dynamic_group_filters:
      pattern: "^(.+),(.+)$"
      prefix: ""
      infix: ","
      suffix: ""
      # Create more user-friendly group names from the auto-determined patterns.
      pattern_replace: "Cloud,"
      
      
## Result is:
    
    {
      "WebServers": [
        "Cloud,WebServers",
        "Cloud,WebServers,DbServers",
        "Cloud,WebServers,DbServers"
      ],
      "WebServers,DbServers": [
        "Cloud,WebServers,DbServers",
        "Cloud,WebServers,DbServers"
      ],
      "all": [
        "Cloud,WebServers",
        "Cloud,WebServers,DbServers",
        "Cloud,WebServers,DbServers"
      ]
    }
    
I like to get result like this:

    {
      "WebServers": [
        "Vm.Name",
        "Vm.Name",
        "Vm.Name"
      ],
      "DbServers": [
        "Vm.Name",
        "Vm.Name"
      ],
      "all": [
        "Vm.Name",
        "Vm.Name",
        "Vm.Name"
      ]
    }

**Comment by marthjod** [comment]
Thanks for the feedback. I will have a look.

**Comment by marthjod** [comment]
I have to disappoint you, unfortunately. As of now, if you set

```yaml
hostname_field_in_user_template: "LABELS"
```

this means that the value for each _LABELS_ template attribute will be interpreted as the VM hostname. This is for scenarios where _vm.Name_ differs from the actual hostname (= FQDN, e.g.) you want to filter by.

In your case, this means you cannot define the _LABELS_ field as hostname field and still get the actual _vm.Name_ as hostname.

I have added a note about these assumptions to the [README](/marthjod/ansible-one-inventory/blob/master/README.md#caveats-assumptions-limitations).

**Comment by marthjod** [comment]
I think label-based grouping is also a valid strategy, though. I will look into it.

**Comment by feldsam** [comment]
Hello, thank you, I written own script https://github.com/FELDSAM-INC/ansible-one-inv

**Comment by marthjod** [comment]
Great, good to know ;)
